url: https://unpredictable.tech
title: unpredictable.tech
tagline: misusing technology to build better software

author:
  name: Victor Pavlychko
  email: 
  url: https://twitter.com/victorpavlychko

menu:
  - title: Blog
    url: /

links:
  - title: Twitter
    icon: bi-twitter
    external_url: https://twitter.com/victorpavlychko
  - title: GitHub
    icon: bi-github
    external_url: https://github.com/victor-pavlychko
  - title: RSS
    icon: bi-rss
    url: /atom.xml

integrations:
  mermaid: true
  goatcounter: https://stats.unpredictable.tech/count

paginate: 5
paginate_path: page:num
permalink: pretty
excerpt_separator: <!-- more -->

plugins:
  - jekyll-paginate
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
